csc:
    # The name of the CSC component that will be provided by the Info endpoint
    name: CSC API
    # The URI of the image file containing the logo of the remote service which SHALL be published online.
    # The image SHALL be in either JPEG or PNG format and not larger than 256x256 pixels.
    logo: https://api.csc.dev/logo.png
    # The ISO 3166-1 [22] Alpha-2 code of the Country where the remote  service provider is established
    # (e.g. ES for Spain).
    region: CZ
    # SignServer workers configuration file
    workerConfigurationFile: /opt/cscapi/workers.yml
    profilesConfigurationDirectory: /opt/cscapi/profiles
    signingSessions:
        expiredSessionsKeepTime: PT1M
        cleanupCronExpression: "0 * * * * *"

# IDP configuration
idp:
    # Base URL of the IDP OpenID Connect endpoint
    baseUrl: https://keycloak.csc.dev:8443/realms/master
    # URL of the JWKS endpoint to retrieve and update the public keys
    jwksUri: https://keycloak.csc.dev:8443/realms/master/protocol/openid-connect/certs
    # URL of the UserInfo endpoint to retrieve user information in exchange for an access token
    userInfoUrl: https://keycloak.csc.dev:8443/realms/master/protocol/openid-connect/userinfo?schema=openid
    # Issuer of the IDP token, used for token validation
    issuer: https://keycloak.csc.dev:8443/realms/master
    # Audience of the IDP token, used for token validation
    audience: da913877-0d65-483e-a18c-4f28d3562297
    # Clock skew in seconds for token validation
    clockSkewSeconds: 5
    # Name of the truststore bundle containing trusted certificates; OPTIONAL
    truststoreBundle: trustedcertificates
    client:
        # Authentication type for the IDP client operations
        # NONE is used for no authentication
        # CERTIFICATE is used for mutual TLS authentication and requires a client certificate
        authType: CERTIFICATE
        # Only used when authorization type is CERTIFICATE
        certificate:
            keystoreBundle: keycloack_client_certificate

# Signing provider configuration
signingProvider:
    # SignServer configuration
    signserver:
        # URL of the SignServer
        url: https://signserver.csc.dev
        # Name of the truststore bundle containing trusted certificates; OPTIONAL
        truststoreBundle: trustedcertificates
        client:
            # Authorization type for the client signing operations
            # BASIC is used for basic authentication, and basic username and password are required
            # CERTIFICATE is used for mutual TLS authentication and requires a client certificate
            authType: CERTIFICATE
            # Only used when authorization type is CERTIFICATE
            certificate:
                keystoreBundle: signserverClient
            # Only used when authorization type is BASIC
            basic:
                # Username for basic authentication
                username: test
                # Password for basic authentication
                password: test
        # Client keystore configuration for admin operations
        admin:
            # Name of the keystore bundle containing the admin certificate and private key
            keystoreBundle: signserverAdmin

# CA provider configuration
caProvider:
    # EJBCA configuration
    ejbca:
        # URL of the EJBCA
        url: https://ejbca.3key.company/ejbca
        # Name of the truststore bundle containing trusted certificates; OPTIONAL
        truststoreBundle: trustedcertificates
        # Admin keystore configuration for RA operations
        admin:
            # Name of the keystore bundle containing the admin certificate and private key
            keystoreBundle: ejbcaAdmin
        credentialProfilesConfigurationFile: /opt/cscapi/credential-profiles-ejbca.yml

# TLS/mTLS configuration
server:
    ssl:
        bundle: web-server
        client-auth: NEED
        # Name of the truststore bundle containing trusted certificates; OPTIONAL
        truststoreBundle: trustedcertificates


# Spring configuration
spring:
    # Jackson configuration, DO NOT CHANGE if you are not familiar with Jackson
    jackson:
        default-property-inclusion: NON_NULL
    ssl:
        bundle:
            jks:
                web-server:
                    keystore:
                        type: "PKCS12"
                        location: /opt/cscapi/certificates/server_keystore.p12
                        password: cscapi
                    truststore:
                        type: "PKCS12"
                        location: /opt/cscapi/certificates/server_truststore.p12
                        password: cscapi

                trustedcertificates:
                    truststore:
                        type: "PKCS12"
                        location: /opt/cscapi/certificates/truststore.p12
                        password: cscapi

                keycloack_client_certificate:
                    keystore:
                        type: "PKCS12"
                        location: /opt/cscapi/certificates/keycloack_client_cert.p12
                        password: cscapi

                ejbcaAdmin:
                    keystore:
                        type: "PKCS12"
                        location: /opt/cscapi/certificates/ejbca_admin_cert.p12
                        password: cscapi

                signserverAdmin:
                    keystore:
                        type: "PKCS12"
                        location: /opt/cscapi/certificates/signserver_admin_cert.p12
                        password: cscapi

                signserverClient:
                    keystore:
                        type: "PKCS12"
                        location: /opt/cscapi/certificates/signserver_client_cert.p12
                        password: cscapi

    # Datasource configuration
    datasource:
        # JDBC URL of the database
        # for PostgreSQL use: jdbc:postgresql://postgresql.csc.dev:5432/csc-dev
        # for MySQL use: jdbc:mysql://mysql.csc.dev:3306/csc-dev
        url: jdbc:mysql://mysql.csc.dev:3306/csc-dev
        # Username to connect to the database
        username: csc
        # Password to connect to the database
        password: password
        # Driver class name of the database
        # for PostgreSQL use: org.postgresql.Driver
        # for MySQL use: com.mysql.cj.jdbc.Driver
#        driver-class-name: com.mysql.cj.jdbc.Driver
    flyway:
        table: "csc_schema_history"
        schemas: "csc-dev"
        locations: "classpath:db/migration,classpath:db/specific/{vendor}"

# Logging configuration
logging:
    level:
        com.czertainly.csc: TRACE
        org.springframework.security: TRACE

springdoc:
    swagger-ui:
        disable-swagger-default-url: true
        configUrl: /openapi/swagger-config
        url: /openapi
    api-docs:
        path: /openapi
